-- ============================================================
-- ATELIER & ART HOUSE - SUPABASE SEED DATA
-- Run in Supabase SQL Editor to populate initial demo catalog
-- ============================================================

-- 1. Seed Artists
INSERT INTO public.artists (id, slug, name, portrait, cover_image, bio, short_bio, location, country, website, instagram, signature_style, mediums, statement, featured, follower_count)
VALUES
  ('artist-1', 'ananya-sen', 'Ananya Sen', '/artists/artist-ananya-sen.svg', '/artworks/painting-monsoon-abstract.svg', 'Ananya Sen is a contemporary abstract painter based in Kolkata. Educated at Visva-Bharati, Santiniketan, her practice meditates on atmospheric water bodies, riverine silt, and fleeting weather phenomena along the eastern delta.', 'Master of delta water movements and indigo atmospheric abstraction.', 'Kolkata, West Bengal', 'India', 'https://atelierarthouse.com/artists/ananya-sen', '@ananyasen.studio', 'Tonal Water Abstraction & Indigo Washes', ARRAY['Oil on Linen', 'Mineral Pigment', 'Handmade Paper', 'Indigo Wash'], 'Painting for me is an act of listening to the river.', true, 2840),
  ('artist-2', 'vikramaditya-roy', 'Vikramaditya Roy', '/artists/artist-vikramaditya-roy.svg', '/artworks/painting-royal-durbar.svg', 'Born into an erstwhile royal atelier family in Jaipur, Vikramaditya Roy deconstructs centuries-old miniature traditions into bold contemporary scale. His works blend deep burgundy velvet tones, pure 24k gold leaf foil, and architectural negative space.', 'Heritage Jaipur miniaturist tradition evolved into royal modern figurative scale.', 'Jaipur, Rajasthan', 'India', 'https://atelierarthouse.com/artists/vikramaditya-roy', '@roy.atelier', 'Neo-Durbar Figurative & Gilt Leaf Geometry', ARRAY['Gold Leaf (24K)', 'Egg Tempera', 'Crushed Lapis', 'Belgian Linen'], 'Royalty is not about pomp; it is about restraint and stillness.', true, 4120),
  ('artist-3', 'tara-deshmukh', 'Tara Deshmukh', '/artists/artist-tara-deshmukh.svg', '/artworks/sculpture-bronze-dancer.svg', 'Tara Deshmukh is a Mumbai-based kinetic sculptor and bronze metallurgist. Trained at the Sir J.J. School of Art, her studio creates fluid lost-wax bronze castings and precision-balanced brass desk kinetic mobiles that oscillate with gentle room air currents.', 'Sculptor of lost-wax cast bronze, fluid dynamism and counter-weighted brass equilibrium.', 'Mumbai, Maharashtra', 'India', 'https://atelierarthouse.com/artists/tara-deshmukh', '@taradeshmukh.bronze', 'Kinetic Equilibrium & Lost-Wax Cast Metal', ARRAY['Cast Bronze', 'Milled Brass', 'Crystalline Marble', 'Smoked Basalt'], 'When a sculpture balances on a pivot of a single millimeter, stillness becomes kinetic music.', true, 3670),
  ('artist-4', 'kaelen-vora', 'Kaelen Vora', '/artists/artist-kaelen-vora.svg', '/artworks/figure-cyber-deva.svg', 'Pioneering India’s collectible figure and neo-mythology design movement from Bengaluru, Kaelen Vora merges cybernetic sci-fi silhouettes with ancient Vedic iconographies into limited-edition cast resin and vinyl art toys.', 'Visionary designer of limited art toys, cyber-mythological figures, and resin artifacts.', 'Bengaluru, Karnataka', 'India', 'https://atelierarthouse.com/artists/kaelen-vora', '@kaelenvora.toys', 'Neo-Vedic Cyber Collectibles & Cast Resin Figures', ARRAY['Designer Vinyl', 'Cast Translucent Resin', 'Cold-Cast Bronze', 'Polystone'], 'Mythology was never static; in another century, our gods would wear cyber-chassis.', true, 5890),
  ('artist-5', 'zoya-mir', 'Zoya Mir', '/artists/artist-zoya-mir.svg', '/artworks/handpainted-crimson-veil.svg', 'Working between Srinagar and New Delhi, Zoya Mir paints heavily textured impasto works using thick palette knives on unprimed rough linen. Her canvases echo the jagged topography of the Pir Panjal mountain range and Kashmiri winter silhouettes.', 'Textured impasto oil painter working with rough Belgian linen and mountainous silences.', 'Srinagar, Jammu & Kashmir', 'India', 'https://atelierarthouse.com/artists/zoya-mir', '@zoyamir.atelier', 'Heavy Impasto Knife Work & Textured Linen', ARRAY['Impasto Oil', 'Raw Pigment', 'Belgian Linen', 'Charcoal Dust'], 'The paint must have body, weight, and shadow of its own.', true, 3210),
  ('artist-6', 'devendra-patil', 'Devendra Patil', '/artists/artist-devendra-patil.svg', '/artworks/sculpture-terracotta-totem.svg', 'Devendra Patil has spent thirty years in Pune mastering pit-fired smoked black terracotta and sand-cast bronze. His work channels prehistoric Deccan archaeological forms, monolithic totems, and tactile stone surfaces.', 'Master sculptor of smoked black terracotta totems and archaeological Deccan forms.', 'Pune, Maharashtra', 'India', 'https://atelierarthouse.com/artists/devendra-patil', '@devendra.patil.studio', 'Smoked Terracotta Totems & Sand-Cast Bronze', ARRAY['Pit-Fired Terracotta', 'Sand-Cast Bronze', 'Basalt Stone', 'Raw Iron'], 'When smoke enters the porous clay in the pit kiln, the earth seals its own secrets.', true, 2450)
ON CONFLICT (id) DO NOTHING;

-- 2. Seed Sample Collections
INSERT INTO public.collections (id, slug, name, subtitle, description, cover_image, badge, curator, featured_on_home)
VALUES
  ('col-1', 'artist-favourites', 'Artist''s Favourites', 'Selected by Ananya Sen & Vikramaditya Roy', 'The personal choices of our resident artists—canvases, bronzes, and objects that hold special significance within their studios.', '/artworks/painting-monsoon-abstract.svg', 'Artist''s Selection', 'Ananya Sen & Vikramaditya Roy', true),
  ('col-2', 'the-home-edit', 'The Home Edit', 'Art for rooms worth remembering', 'Statement artworks, serene bedroom horizontals, and architectural console sculptures curated to complete real living spaces.', '/rooms/room-living-room.svg', 'Interior Curation', 'Atelier Architecture Bureau', true),
  ('col-3', 'one-of-one', 'The Artist''s Hand — One of One', 'Original hand-painted masterworks', 'Hand-painted singular canvases where no two pieces are alike. Complete with hot-wax sealed provenance and certificates.', '/artworks/handpainted-sacred-geometry.svg', 'One of One', 'Curatorial Board', true),
  ('col-4', 'sculptures-and-collectibles', 'Sculptures & Collectible Figures', 'Three-dimensional art objects for connoisseurs', 'From lost-wax cast bronzes to limited-edition cyber-mythological art toys and solid brass mobiles.', '/artworks/sculpture-bronze-dancer.svg', 'Limited Casts', 'Tara Deshmukh & Kaelen Vora', true),
  ('col-5', 'under-5000', 'The Gift Edit: Under ₹5,000', 'Archival prints and desk sculptures', 'Original limited edition prints on cotton rag, solid brass desk objects, and artisanal vessels for discerning recipients.', '/artworks/object-brass-sundial.svg', 'Collector Gifts', 'Atelier Concierge', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Seed Sample Coupons
INSERT INTO public.coupons (code, discount_percent, min_order_amount, is_active)
VALUES
  ('COLLECTOR10', 10, 2500, true),
  ('FIRSTACQUISITION', 15, 5000, true),
  ('CONNOISSEUR', 20, 20000, true)
ON CONFLICT (code) DO NOTHING;
