-- ============================================================
-- ATELIER HOME & LIVING - PRODUCTION SEED DATA
-- 40 Curated Products across: wall-art, sculptures, decorative-pieces
-- ============================================================

INSERT INTO public.products (
  id, slug, name, category, subcategory, price, original_price,
  description, short_description, images, thumbnail, material, medium,
  dimensions, stock, is_active, is_featured, is_new, is_bestseller,
  is_artist_favorite, rating, review_count, created_at, updated_at
) VALUES
  (
    'art-01',
    'monsoon-over-the-ghats',
    'Monsoon Over the Ghats',
    'wall-art',
    'abstract',
    34500,
    38000,
    'A monumental abstract work capturing the deep atmospheric shifts of eastern monsoon skies above ancient river stairways. Layered indigo mineral washes converge with raw gold leaf river reflections and charcoal clouds.',
    'Atmospheric indigo and 22k gold leaf abstract oil on stretched Belgian linen.',
    '{"/artworks/painting-monsoon-abstract.svg","/artworks/painting-kashi-reverie.svg","/artworks/painting-silent-horizon.svg"}',
    '/artworks/painting-monsoon-abstract.svg',
    'Stretched Linen Canvas, Timber Stretcher Bars',
    'Oil and 22K Gold Leaf on Belgian Linen',
    '{"width":120,"height":150,"depth":4,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    true,
    true,
    true,
    5,
    4,
    '2026-02-01T00:00:00Z',
    '2026-02-15T00:00:00Z'
  ),
  (
    'art-02',
    'solitude-in-burnt-ochre',
    'Solitude in Burnt Ochre',
    'wall-art',
    'contemporary',
    28000,
    32000,
    'Geometric architectural planes in warm burnt ochre, sandstone bone, and deep obsidian charcoal. The painting evokes the solitary silence of desert ramparts at sunset.',
    'Warm earth pigments and minimal geometric arch composition on heavy canvas.',
    '{"/artworks/painting-solitude-in-ochre.svg","/artworks/painting-rajasthan-winds.svg"}',
    '/artworks/painting-solitude-in-ochre.svg',
    'Natural Raw Duck Canvas, Pine Wood Frame',
    'Mineral Earth Pigments and Acrylic on Canvas',
    '{"width":100,"height":120,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    false,
    false,
    false,
    4.8,
    3,
    '2026-01-10T00:00:00Z',
    '2026-02-01T00:00:00Z'
  ),
  (
    'art-03',
    'echoes-of-the-durbar',
    'Echoes of the Durbar',
    'wall-art',
    'portraits',
    48000,
    54000,
    'A majestic contemporary royal figurative composition. Deep burgundy background enveloped by arching 24K gold leaf outlines and silhouette of seated royal dignity.',
    'Deep royal burgundy, lapis accents, and 24K pure gold leaf on primed linen.',
    '{"/artworks/painting-royal-durbar.svg","/artworks/painting-monsoon-abstract.svg"}',
    '/artworks/painting-royal-durbar.svg',
    'Linen on Kiln-Dried Teak Stretcher',
    'Egg Tempera, Lapis Lazuli, and 24K Gold Leaf on Linen',
    '{"width":110,"height":140,"depth":4,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    false,
    true,
    true,
    5,
    6,
    '2025-11-20T00:00:00Z',
    '2026-02-10T00:00:00Z'
  ),
  (
    'art-04',
    'silent-horizon-no-4',
    'Silent Horizon No. 4',
    'wall-art',
    'landscapes',
    24500,
    27000,
    'A wide, meditative horizontal landscape reduced to two pure tonal fields: warm bone ivory sky and rich obsidian charcoal earth, divided by a razor-thin gilded gold horizon line.',
    'Meditative tonal color field divided by antique gold leaf horizon line.',
    '{"/artworks/painting-silent-horizon.svg","/artworks/painting-solitude-in-ochre.svg"}',
    '/artworks/painting-silent-horizon.svg',
    'Wide Panorama Gallery Canvas',
    'Oil and Gold Leaf on Stretched Canvas',
    '{"width":160,"height":100,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    true,
    false,
    false,
    4.9,
    2,
    '2026-02-05T00:00:00Z',
    '2026-02-18T00:00:00Z'
  ),
  (
    'art-05',
    'kashi-reverie-in-dusk',
    'Kashi Reverie in Dusk',
    'wall-art',
    'contemporary',
    36000,
    40000,
    'Dramatic temple spires towering over evening river ghats in rich terracotta, deep charcoal, and warm amber tones with floating oil lamp reflections on the sacred waters.',
    'Evocative evening ghats rendered in deep charcoal, terracotta, and gold reflection.',
    '{"/artworks/painting-kashi-reverie.svg"}',
    '/artworks/painting-kashi-reverie.svg',
    'Belgian Linen on Hardwood Stretcher',
    'Charcoal, Silt, and Oil on Linen',
    '{"width":100,"height":135,"depth":4,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    false,
    true,
    false,
    5,
    5,
    '2025-12-15T00:00:00Z',
    '2026-01-20T00:00:00Z'
  ),
  (
    'art-06',
    'botanical-nocturne',
    'Botanical Nocturne',
    'wall-art',
    'abstract',
    29500,
    33000,
    'Rich deep emerald and midnight velvet background with sweeping antique-gold botanical foliage lines that rise towards a luminous celestial ivory moon disk.',
    'Emerald green nocturne with delicate antique gold floral stems and celestial moon.',
    '{"/artworks/painting-botanical-nocturne.svg"}',
    '/artworks/painting-botanical-nocturne.svg',
    'Triple-Primed Cotton Canvas',
    'Pigment and Metallic Gold on Heavy Canvas',
    '{"width":90,"height":120,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    true,
    false,
    true,
    4.9,
    3,
    '2026-02-10T00:00:00Z',
    '2026-02-18T00:00:00Z'
  ),
  (
    'art-07',
    'geometric-rapture',
    'Geometric Rapture',
    'wall-art',
    'contemporary',
    22000,
    25000,
    'Bold contemporary hard-edge geometry combining triangular prisms, concentric circles, and intersecting linear rules in deep burgundy, warm ivory, and antique gold.',
    'Contemporary hard-edge geometric abstraction in burgundy, gold, and bone.',
    '{"/artworks/painting-geometric-rapture.svg"}',
    '/artworks/painting-geometric-rapture.svg',
    'Archival Birch Panel with Linen Surface',
    'Acrylic and Screen Ink on Linen Panel',
    '{"width":90,"height":90,"depth":3,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    false,
    false,
    false,
    4.7,
    2,
    '2025-10-18T00:00:00Z',
    '2026-01-05T00:00:00Z'
  ),
  (
    'art-08',
    'whispering-dunes',
    'Whispering Dunes',
    'wall-art',
    'landscapes',
    26500,
    30000,
    'Rolling curvilinear sand dunes rendered in natural desert sand textures, warm sienna, and antique gold sun disk under a serene ivory sky.',
    'Curvilinear sand textures and warm sienna dunes with radiant gold sun.',
    '{"/artworks/painting-rajasthan-winds.svg"}',
    '/artworks/painting-rajasthan-winds.svg',
    'Natural Linen Canvas on Pine Stretcher',
    'Desert Sand and Oil on Canvas',
    '{"width":140,"height":90,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    false,
    false,
    false,
    4.8,
    3,
    '2025-09-12T00:00:00Z',
    '2025-11-20T00:00:00Z'
  ),
  (
    'art-09',
    'portrait-of-an-unknown-poet',
    'Portrait of an Unknown Poet',
    'wall-art',
    'portraits',
    31000,
    35000,
    'An enigmatic, deeply contemplative modern portrait. Angular facial planes emerge from bone ivory and charcoal shadows, highlighted by a burgundy cravat and gold line.',
    'Expressive angular figurative portrait in muted bone, charcoal, and burgundy.',
    '{"/artworks/painting-portrait-poet.svg"}',
    '/artworks/painting-portrait-poet.svg',
    'Stretched Linen on Kiln-Dried Pine',
    'Oil and Charcoal on Belgian Linen',
    '{"width":90,"height":120,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    false,
    false,
    true,
    5,
    4,
    '2025-11-05T00:00:00Z',
    '2026-01-15T00:00:00Z'
  ),
  (
    'art-10',
    'celestial-tides',
    'Celestial Tides',
    'wall-art',
    'abstract',
    32000,
    36000,
    'Concentric orbital brass and gold leaf rings sweeping across deep oceanic teal and obsidian vortex, crowned with a burgundy trajectory arc.',
    'Oceanic teal vortex with concentric gold orbit lines and celestial sphere.',
    '{"/artworks/painting-celestial-tides.svg"}',
    '/artworks/painting-celestial-tides.svg',
    'Square Heavy Stretched Linen',
    'Oil, Enamel, and Antique Gold on Linen',
    '{"width":110,"height":110,"depth":4,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    true,
    false,
    false,
    4.9,
    2,
    '2026-01-28T00:00:00Z',
    '2026-02-12T00:00:00Z'
  ),
  (
    'art-11',
    'passage-through-hawa',
    'Passage Through Hawa',
    'wall-art',
    'contemporary',
    27500,
    31000,
    'A multi-foil Jharokha arch rendered with serene architectural negative space in bone ivory, deep charcoal, and glowing gold heart.',
    'Heritage Rajput archway geometry distilled into pure minimalist ivory and gold.',
    '{"/artworks/painting-jaipur-arch.svg"}',
    '/artworks/painting-jaipur-arch.svg',
    'Natural Canvas with Mineral Texture',
    'Lime Plaster, Sandstone Wash, and Gold on Canvas',
    '{"width":90,"height":120,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    false,
    true,
    false,
    4.8,
    3,
    '2025-10-02T00:00:00Z',
    '2025-12-14T00:00:00Z'
  ),
  (
    'art-12',
    'shadows-in-still-water',
    'Shadows in Still Water',
    'wall-art',
    'abstract',
    21500,
    24000,
    'Quiet rectangular color blocks in obsidian and antique bone, accented by gold orb and square reflections across a still mirror horizon.',
    'Monochromatic ink wash and antique gold geometry in pure contemplative balance.',
    '{"/artworks/painting-shadows-time.svg"}',
    '/artworks/painting-shadows-time.svg',
    'Natural Heavy Canvas',
    'Ink Wash, Oil, and Gold on Canvas',
    '{"width":90,"height":120,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    false,
    false,
    false,
    4.7,
    1,
    '2025-08-19T00:00:00Z',
    '2025-10-10T00:00:00Z'
  ),
  (
    'art-13',
    'the-cosmologists-map',
    'The Cosmologist''s Map',
    'wall-art',
    'hand-painted',
    42000,
    47000,
    'A dramatic tactile one-of-one masterwork. Heavy impasto oil paste encrusted with 22K gold foil lozenge and deep burgundy concentric circles, bearing the artist’s vermilion seal.',
    'One-of-One textured oil and 22K gold foil with vermilion artist seal.',
    '{"/artworks/handpainted-sacred-geometry.svg"}',
    '/artworks/handpainted-sacred-geometry.svg',
    'Belgian Linen on Hand-Chamfered Mahogany Stretcher',
    'Hand-Milled Mineral Oil & 22K Gold Foil on Raw Belgian Linen',
    '{"width":100,"height":130,"depth":4.5,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    true,
    true,
    true,
    5,
    7,
    '2026-02-14T00:00:00Z',
    '2026-02-18T00:00:00Z'
  ),
  (
    'art-14',
    'the-crimson-veil',
    'The Crimson Veil',
    'wall-art',
    'hand-painted',
    38500,
    42000,
    'Sumptuous deep burgundy and carmine oil layers applied with flexible steel knives over raw textured linen, pierced by an antique gold meridian rule.',
    'One-of-One heavy impasto oil on raw Belgian linen with gold meridian.',
    '{"/artworks/handpainted-crimson-veil.svg"}',
    '/artworks/handpainted-crimson-veil.svg',
    'Raw Belgian Linen Canvas',
    'Impasto Oil & Metallic Pigment on Linen',
    '{"width":95,"height":125,"depth":4,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    true,
    false,
    true,
    5,
    4,
    '2026-01-20T00:00:00Z',
    '2026-02-05T00:00:00Z'
  ),
  (
    'art-15',
    'passage-at-high-altitude',
    'Passage at High Altitude',
    'wall-art',
    'hand-painted',
    34000,
    38000,
    'Chiseled palette knife mountain ridges in pure bone white and slate obsidian, separated from deep valley darkness by an antique gold fault line.',
    'One-of-One palette knife Himalayan ridge study in bone and obsidian.',
    '{"/artworks/handpainted-mountain-passage.svg"}',
    '/artworks/handpainted-mountain-passage.svg',
    'Coarse Hand-Woven Linen',
    'Heavy Body Oil on Coarse Linen',
    '{"width":135,"height":95,"depth":4,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    false,
    true,
    false,
    4.9,
    3,
    '2025-11-14T00:00:00Z',
    '2026-01-02T00:00:00Z'
  ),
  (
    'art-16',
    'echo-of-the-potters-hand',
    'Echo of the Potter''s Hand',
    'wall-art',
    'hand-painted',
    25000,
    28000,
    'Natural baked terracotta clay slips and charred wood charcoal dust painted onto hand-woven jute canvas in concentric primordial circles.',
    'One-of-One pit-fired clay slips and charcoal on hand-woven jute canvas.',
    '{"/artworks/handpainted-terracotta-vessel.svg"}',
    '/artworks/handpainted-terracotta-vessel.svg',
    'Natural Jute Canvas on Teak Frame',
    'Natural Terracotta Slips & Charcoal on Jute',
    '{"width":90,"height":120,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    true,
    false,
    false,
    4.8,
    2,
    '2026-01-10T00:00:00Z',
    '2026-02-01T00:00:00Z'
  ),
  (
    'art-17',
    'golden-hour-at-amber',
    'Golden Hour at Amber',
    'wall-art',
    'hand-painted',
    39000,
    44000,
    'Gilded antique gold leaf gradient meeting an intricate starburst mandala in deep obsidian and bone ivory.',
    'One-of-One hand-leafed gold gradient and obsidian starburst mandala.',
    '{"/artworks/handpainted-golden-hour.svg"}',
    '/artworks/handpainted-golden-hour.svg',
    'Linen Canvas on Timber Stretcher',
    '22K Gold Leaf, Resin, and Ink on Heavy Linen',
    '{"width":95,"height":125,"depth":4,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    false,
    true,
    true,
    5,
    5,
    '2025-12-01T00:00:00Z',
    '2026-01-20T00:00:00Z'
  ),
  (
    'art-18',
    'midnight-rhapsody-in-charcoal',
    'Midnight Rhapsody in Charcoal',
    'wall-art',
    'hand-painted',
    29000,
    33000,
    'Smoky compressed willow charcoal dust and raw beeswax on heavy cold-press cotton rag with an embedded gold leaf moon orb.',
    'One-of-One willow charcoal and antique gold leaf moon on raw cotton rag.',
    '{"/artworks/handpainted-dark-rhapsody.svg"}',
    '/artworks/handpainted-dark-rhapsody.svg',
    '640gsm Arches Cotton Rag Mounted on Wood',
    'Willow Charcoal, Beeswax, and Gold Leaf on Heavy Rag',
    '{"width":90,"height":120,"depth":3.5,"unit":"cm"}'::jsonb,
    1,
    true,
    false,
    true,
    false,
    false,
    4.8,
    2,
    '2026-01-25T00:00:00Z',
    '2026-02-14T00:00:00Z'
  ),
  (
    'art-19',
    'the-motion-of-stillness',
    'The Motion of Stillness',
    'sculptures',
    'bronze',
    45000,
    50000,
    'A lost-wax cast bronze sculpture capturing the fluid spiral twist of a classical dancer at the apex of balance. Hand-burnished with a deep warm bronze and verdigris patina, mounted on a solid smoked basalt plinth.',
    'Lost-wax cast bronze on smoked basalt pedestal with warm burnished patina.',
    '{"/artworks/sculpture-bronze-dancer.svg","/artworks/sculpture-serpent-form.svg"}',
    '/artworks/sculpture-bronze-dancer.svg',
    'Bronze, Smoked Basalt Base',
    'Lost-Wax Cast Bronze with Verdigris Patina',
    '{"width":32,"height":68,"depth":28,"unit":"cm"}'::jsonb,
    2,
    true,
    true,
    true,
    true,
    true,
    5,
    6,
    '2026-01-05T00:00:00Z',
    '2026-02-10T00:00:00Z'
  ),
  (
    'art-20',
    'torso-in-makrana-white',
    'Torso in Makrana White',
    'sculptures',
    'marble',
    39500,
    44000,
    'Direct-carved crystalline Makrana white marble sculpture representing the subtle curvature of human breath. Satin hand-honed finish on an obsidian granite base.',
    'Hand-carved crystalline Makrana white marble on black granite block.',
    '{"/artworks/sculpture-marble-torso.svg"}',
    '/artworks/sculpture-marble-torso.svg',
    'Natural Marble, Black Granite',
    'Direct-Carved Makrana Crystalline Marble',
    '{"width":28,"height":58,"depth":24,"unit":"cm"}'::jsonb,
    1,
    true,
    true,
    false,
    false,
    false,
    4.9,
    4,
    '2025-11-10T00:00:00Z',
    '2026-01-12T00:00:00Z'
  ),
  (
    'art-21',
    'ancestral-totem-iii',
    'Ancestral Totem III',
    'sculptures',
    'terracotta',
    18500,
    21000,
    'Smoked black terracotta totem with hand-carved geometric incised lines and natural burnished river-stone finish. Pit-fired with dried tamarind wood.',
    'Pit-fired smoked black terracotta totem with tribal incisions.',
    '{"/artworks/sculpture-terracotta-totem.svg"}',
    '/artworks/sculpture-terracotta-totem.svg',
    'River Clay, Natural Black Smoke Patina',
    'Pit-Fired Smoked Terracotta',
    '{"width":22,"height":62,"depth":22,"unit":"cm"}'::jsonb,
    3,
    true,
    false,
    false,
    true,
    false,
    4.8,
    5,
    '2025-09-30T00:00:00Z',
    '2025-12-05T00:00:00Z'
  ),
  (
    'art-22',
    'equilibrium-kinetic-object',
    'Equilibrium (Kinetic Object)',
    'sculptures',
    'desk-objects',
    16500,
    19000,
    'Counter-weighted raw brushed brass kinetic mobile that sits on a needle-point pivot. Subtle room air movements induce a hypnotic, silent 360-degree rotation.',
    'Counter-weighted raw brass kinetic mobile on low-friction stainless needle pivot.',
    '{"/artworks/sculpture-kinetic-brass.svg"}',
    '/artworks/sculpture-kinetic-brass.svg',
    'C360 Brass, 316 Stainless Steel Pin',
    'Milled Solid Brass and Enamel on Steel Pivot',
    '{"width":45,"height":38,"depth":15,"unit":"cm"}'::jsonb,
    4,
    true,
    true,
    true,
    true,
    true,
    5,
    9,
    '2026-01-18T00:00:00Z',
    '2026-02-16T00:00:00Z'
  ),
  (
    'art-23',
    'monolith-in-cast-basalt',
    'Monolith in Cast Basalt',
    'sculptures',
    'sculptures',
    32000,
    36000,
    'Heavy cast volcanic basalt monolith featuring a central 24K gold-leaf slit recess and geometric negative-space void. Severe, architectural, and deeply grounding.',
    'Cast volcanic basalt monolith with central 24K gold-leaf slit inlay.',
    '{"/artworks/sculpture-brutalist-arch.svg"}',
    '/artworks/sculpture-brutalist-arch.svg',
    'Natural Basalt Aggregate, Hardwood Sub-base',
    'Cast Basalt and 24K Gold Leaf',
    '{"width":26,"height":54,"depth":18,"unit":"cm"}'::jsonb,
    2,
    true,
    false,
    false,
    false,
    false,
    4.8,
    3,
    '2025-10-15T00:00:00Z',
    '2025-12-20T00:00:00Z'
  ),
  (
    'art-24',
    'kundalini-spiral',
    'Kundalini Spiral',
    'sculptures',
    'bronze',
    36000,
    40000,
    'Rising spiral helix in hot-forged blackened iron and polished cast bronze terminal sphere. Represents latent energetic force ascending through cosmic axis.',
    'Ascending forged iron helix crowned with polished bronze terminal sphere.',
    '{"/artworks/sculpture-serpent-form.svg"}',
    '/artworks/sculpture-serpent-form.svg',
    'Iron, Bronze, Obsidian Base',
    'Hot-Forged Wrought Iron and Polished Bronze',
    '{"width":24,"height":72,"depth":24,"unit":"cm"}'::jsonb,
    2,
    true,
    false,
    true,
    false,
    false,
    4.9,
    4,
    '2026-01-22T00:00:00Z',
    '2026-02-15T00:00:00Z'
  ),
  (
    'art-25',
    'cyber-deva-archetype-01',
    'Cyber Deva: Archetype 01',
    'sculptures',
    'collectible-figures',
    14500,
    16500,
    'A limited-edition designer vinyl and cast resin collectible figure. Matte obsidian body chassis with electroplated 18K antique gold faceplate visor and floating cybernetic halo ring.',
    'Matte obsidian designer vinyl figure with 18k electroplated gold visor and halo.',
    '{"/artworks/figure-cyber-deva.svg","/artworks/figure-celestial-courier.svg"}',
    '/artworks/figure-cyber-deva.svg',
    'High-Density Vinyl, Resin, Brass Inlays',
    'Matte Designer Vinyl, Electroplated ABS, and Cast Resin',
    '{"width":18,"height":36,"depth":16,"unit":"cm"}'::jsonb,
    5,
    true,
    true,
    true,
    true,
    true,
    5,
    14,
    '2026-01-08T00:00:00Z',
    '2026-02-18T00:00:00Z'
  ),
  (
    'art-26',
    'astral-nomad',
    'Astral Nomad (Edition of 99)',
    'sculptures',
    'collectible-figures',
    18000,
    21000,
    'Translucent smoky cast resin astronaut figure with internal gold leaf flakes and a polished obsidian visor plate. Includes removable antique brass telemetry staff.',
    'Translucent resin astronaut figure with suspended gold leaf flakes.',
    '{"/artworks/figure-astral-voyager.svg"}',
    '/artworks/figure-astral-voyager.svg',
    'Cast Resin, Solid Brass Staff',
    'Clear & Smoky Polyurethane Resin, 24K Gold Leaf Inclusions',
    '{"width":16,"height":32,"depth":15,"unit":"cm"}'::jsonb,
    3,
    true,
    true,
    true,
    false,
    false,
    4.9,
    8,
    '2026-02-02T00:00:00Z',
    '2026-02-14T00:00:00Z'
  ),
  (
    'art-27',
    'the-wandering-zenite',
    'The Wandering Zenite',
    'sculptures',
    'collectible-figures',
    12500,
    14500,
    'Cold-cast polystone figure of a solitary wandering monk clad in an oversized burgundy kasa hat and weathered charcoal robes with antique gold sash.',
    'Cold-cast polystone figure with hand-finished burgundy kasa hat and fabric mantle.',
    '{"/artworks/figure-ronin-monk.svg"}',
    '/artworks/figure-ronin-monk.svg',
    'Polystone, Cotton Mantle, Brass Sword Hilt',
    'Cold-Cast Polystone and Hand-Dyed Fabric',
    '{"width":18,"height":34,"depth":18,"unit":"cm"}'::jsonb,
    4,
    true,
    false,
    false,
    true,
    false,
    4.8,
    11,
    '2025-11-18T00:00:00Z',
    '2026-01-10T00:00:00Z'
  ),
  (
    'art-28',
    'solar-golem-iv',
    'Solar Golem IV',
    'sculptures',
    'collectible-figures',
    9500,
    11000,
    'Heavy cast terracotta designer figure with boulder-like articulated anatomy and a polished gold-leaf chest core that catches ambient room light.',
    'Cast baked terracotta designer figure with 22k gold leaf chest core.',
    '{"/artworks/figure-solar-golem.svg"}',
    '/artworks/figure-solar-golem.svg',
    'Baked Terracotta Clay',
    'High-Fired Terracotta and 22K Gold Leaf',
    '{"width":16,"height":26,"depth":14,"unit":"cm"}'::jsonb,
    6,
    true,
    false,
    true,
    false,
    false,
    4.7,
    5,
    '2026-01-15T00:00:00Z',
    '2026-02-12T00:00:00Z'
  ),
  (
    'art-29',
    'nocturnal-familiar-kitsune',
    'Nocturnal Familiar',
    'sculptures',
    'collectible-figures',
    8500,
    9900,
    'Glossy midnight burgundy ceramic fox spirit figure wearing a bone ivory Noh mask and gold jewel core.',
    'High-gloss midnight burgundy ceramic figure with bone Noh mask.',
    '{"/artworks/figure-shadow-kitsune.svg"}',
    '/artworks/figure-shadow-kitsune.svg',
    'High-Fire Porcelain Ceramic',
    'Glazed Ceramic and Polished Brass Core',
    '{"width":14,"height":28,"depth":12,"unit":"cm"}'::jsonb,
    5,
    true,
    false,
    false,
    true,
    false,
    4.9,
    9,
    '2025-10-20T00:00:00Z',
    '2025-12-18T00:00:00Z'
  ),
  (
    'art-30',
    'hermes-of-the-void',
    'Hermes of the Void',
    'sculptures',
    'collectible-figures',
    16000,
    18500,
    'Architectural winged messenger figure in electroplated antique brass, matte obsidian torso, and smoke acrylic visor.',
    'Electroplated antique brass & smoke acrylic winged messenger figure.',
    '{"/artworks/figure-celestial-courier.svg"}',
    '/artworks/figure-celestial-courier.svg',
    'Zinc Alloy, Brass, Acrylic',
    'Electroplated Brass, Die-Cast Zinc, and Acrylic',
    '{"width":22,"height":35,"depth":16,"unit":"cm"}'::jsonb,
    2,
    true,
    true,
    true,
    false,
    true,
    5,
    7,
    '2026-02-01T00:00:00Z',
    '2026-02-17T00:00:00Z'
  ),
  (
    'art-31',
    'study-of-niloufar',
    'Study of Niloufar (Print)',
    'wall-art',
    'fine-art-prints',
    4999,
    6500,
    'Archival pigment print on 310gsm Hahnemühle German Etching paper. Minimalist botanical ink lotus with wide archival museum white mat border, hand-numbered and signed by Ananya Sen.',
    'Archival pigment print on 310gsm Hahnemühle paper, signed edition of 100.',
    '{"/artworks/print-lotus-monochrome.svg"}',
    '/artworks/print-lotus-monochrome.svg',
    '310gsm 100% Cotton Rag Acid-Free Paper',
    'Archival Giclée Pigment Print',
    '{"width":50,"height":70,"depth":0.1,"unit":"cm"}'::jsonb,
    12,
    true,
    true,
    false,
    true,
    false,
    4.9,
    16,
    '2025-10-01T00:00:00Z',
    '2026-01-10T00:00:00Z'
  ),
  (
    'art-32',
    'haveli-shadows-lithograph',
    'Haveli Shadows (Edition 24/50)',
    'wall-art',
    'limited-editions',
    7500,
    9000,
    'Hand-pulled two-color stone lithograph on French Velin d’Arches paper. Features geometric haveli balcony shadows in charcoal black and warm ochre dots.',
    'Hand-pulled stone lithograph on French cotton rag, numbered edition of 50.',
    '{"/artworks/print-haveli-facade.svg"}',
    '/artworks/print-haveli-facade.svg',
    'Archival Cotton Rag Paper',
    'Stone Lithograph on 250gsm Velin d’Arches',
    '{"width":60,"height":80,"depth":0.1,"unit":"cm"}'::jsonb,
    8,
    true,
    false,
    false,
    true,
    true,
    5,
    9,
    '2025-11-20T00:00:00Z',
    '2026-02-01T00:00:00Z'
  ),
  (
    'art-33',
    'tantra-and-cosmos-no-2',
    'Tantra & Cosmos No. 2',
    'wall-art',
    'limited-editions',
    3499,
    4200,
    'Silkscreen print with hand-embossed blind debossing and metallic bronze ink over deep obsidian black paper. Yantra geometry meets minimal cosmic order.',
    'Embossed silkscreen with metallic bronze ink on black paper.',
    '{"/artworks/print-cosmic-mandala.svg"}',
    '/artworks/print-cosmic-mandala.svg',
    '350gsm Colorplan Ebony Card',
    'Silkscreen and Blind Embossing on Black Card',
    '{"width":50,"height":50,"depth":0.1,"unit":"cm"}'::jsonb,
    15,
    true,
    false,
    true,
    true,
    false,
    4.8,
    12,
    '2026-01-12T00:00:00Z',
    '2026-02-15T00:00:00Z'
  ),
  (
    'art-34',
    'deccan-topography',
    'Deccan Topography',
    'wall-art',
    'fine-art-prints',
    2499,
    3200,
    'Minimalist topographical contour print tracing the volcanic basalt plateaus of the Deccan Traps on warm bone archival paper with a burgundy core basin.',
    'Minimalist topographical print of Deccan plateau contours on warm bone paper.',
    '{"/artworks/print-deccan-plateau.svg"}',
    '/artworks/print-deccan-plateau.svg',
    '280gsm Rag Paper',
    'Archival Giclée Print on Natural Rag',
    '{"width":70,"height":50,"depth":0.1,"unit":"cm"}'::jsonb,
    20,
    true,
    false,
    false,
    true,
    false,
    4.7,
    14,
    '2025-08-10T00:00:00Z',
    '2025-11-01T00:00:00Z'
  ),
  (
    'art-35',
    'steps-to-the-river',
    'Steps to the River',
    'wall-art',
    'fine-art-prints',
    3999,
    4800,
    'Woodblock reduction print on handmade Japanese Kozo mulberry paper. The stepped stone ghats lead to calm waters with twin antique gold horizon rules.',
    'Woodblock print on Japanese Kozo paper depicting Banaras ghat steps.',
    '{"/artworks/print-banaras-ghats.svg"}',
    '/artworks/print-banaras-ghats.svg',
    'Japanese Kozo Mulberry Paper',
    'Woodblock Print on Kozo Paper',
    '{"width":50,"height":70,"depth":0.1,"unit":"cm"}'::jsonb,
    9,
    true,
    false,
    false,
    false,
    false,
    4.8,
    6,
    '2025-09-05T00:00:00Z',
    '2025-12-10T00:00:00Z'
  ),
  (
    'art-36',
    'chamber-of-echoes',
    'Chamber of Echoes',
    'wall-art',
    'limited-editions',
    4500,
    5200,
    'Giclée art print featuring a luminous gold sphere centered in a dark architectural chamber bordered in rich deep burgundy.',
    'Giclée print of gold sphere in deep burgundy and obsidian chamber.',
    '{"/artworks/print-silent-chamber.svg"}',
    '/artworks/print-silent-chamber.svg',
    '100% Cotton Rag Paper',
    'Archival Giclée on 300gsm Cotton Rag',
    '{"width":50,"height":70,"depth":0.1,"unit":"cm"}'::jsonb,
    11,
    true,
    false,
    true,
    false,
    false,
    4.9,
    4,
    '2026-01-05T00:00:00Z',
    '2026-02-10T00:00:00Z'
  ),
  (
    'art-37',
    'astrolabe-minimalist-paperweight',
    'Astrolabe Minimalist Paperweight',
    'decorative-pieces',
    'desk-objects',
    4999,
    5900,
    'Precision-milled solid antique brass desk paperweight and sundial with laser-engraved celestial coordinates and chamfered hand-polished edges.',
    'Solid milled antique brass celestial paperweight and gnomon dial.',
    '{"/artworks/object-brass-sundial.svg"}',
    '/artworks/object-brass-sundial.svg',
    'Solid C360 Brass, Leather Bottom Base',
    'Milled Solid Brass with Natural Oxidation Seal',
    '{"width":14,"height":14,"depth":4,"unit":"cm"}'::jsonb,
    8,
    true,
    true,
    true,
    true,
    true,
    5,
    18,
    '2026-01-10T00:00:00Z',
    '2026-02-15T00:00:00Z'
  ),
  (
    'art-38',
    'basalt-ikebana-vessel',
    'Basalt Ikebana Vessel',
    'decorative-pieces',
    'decorative-objects',
    6800,
    8000,
    'Hand-chiseled raw volcanic basalt stone vessel designed to hold a single dry botanical stem or solitary branch. Smooth hand-honed aperture with rustic natural exterior.',
    'Hand-chiseled volcanic basalt single-branch vessel with brass stem pin.',
    '{"/artworks/object-brutalist-vessel.svg"}',
    '/artworks/object-brutalist-vessel.svg',
    'Natural Basalt Stone, Brass Pin',
    'Hand-Chiseled Volcanic Basalt Stone',
    '{"width":16,"height":22,"depth":12,"unit":"cm"}'::jsonb,
    4,
    true,
    false,
    false,
    true,
    false,
    4.9,
    7,
    '2025-11-05T00:00:00Z',
    '2026-01-20T00:00:00Z'
  ),
  (
    'art-39',
    'sanctum-brass-incense-temple',
    'Sanctum Brass Incense Burner',
    'decorative-pieces',
    'desk-objects',
    3800,
    4500,
    'Solid cast brass architectural tier burner with internal ash reservoir and chimney slit that releases vertical ribbon smoke plumes.',
    'Solid cast brass tiered incense burner with concealed ash tray.',
    '{"/artworks/object-incense-temple.svg"}',
    '/artworks/object-incense-temple.svg',
    'Lead-Free C260 Brass',
    'Solid Sand-Cast Brass with Antique Burnish',
    '{"width":12,"height":18,"depth":12,"unit":"cm"}'::jsonb,
    14,
    true,
    false,
    true,
    true,
    false,
    4.8,
    22,
    '2026-01-14T00:00:00Z',
    '2026-02-18T00:00:00Z'
  ),
  (
    'art-40',
    'orb-of-stillness-bookend-set',
    'Orb of Stillness Bookend Set',
    'decorative-pieces',
    'decorative-objects',
    5500,
    6500,
    'Pair of hand-turned solid forest green Bidasar marble spheres resting on heavy blackened steel L-bracket bookend supports.',
    'Pair of solid green Bidasar marble spheres on blackened steel bookends.',
    '{"/artworks/object-marble-sphere.svg"}',
    '/artworks/object-marble-sphere.svg',
    'Natural Marble, Cold-Rolled Steel',
    'Bidasar Forest Green Marble & Blackened Steel',
    '{"width":14,"height":16,"depth":12,"unit":"cm"}'::jsonb,
    6,
    true,
    false,
    false,
    true,
    false,
    5,
    11,
    '2025-10-10T00:00:00Z',
    '2026-01-05T00:00:00Z'
  );

-- Seed Active Promotional Coupons
INSERT INTO public.coupons (code, discount_percent, min_order_amount, is_active) VALUES
  ('COLLECTOR10', 10, 0, true),
  ('FIRSTACQUISITION', 15, 0, true),
  ('CONNOISSEUR', 20, 0, true)
ON CONFLICT (code) DO UPDATE SET discount_percent = EXCLUDED.discount_percent, is_active = true;
